-- MySQL Script generated by MySQL Workbench
-- 06/13/15 13:55:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lifecoach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lifecoach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lifecoach` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lifecoach` ;

-- -----------------------------------------------------
-- Table `lifecoach`.`awarenessinformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`awarenessinformation` (
  `awrenessinfoId` INT(11) NOT NULL,
  `awarenessInformation` VARCHAR(1000) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`awrenessinfoId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`CareGiiver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`CareGiiver` (
  `careGiverId` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(300) NOT NULL,
  `lastName` VARCHAR(300) NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`careGiverId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`lifestylemeasuremnt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`lifestylemeasuremnt` (
  `lifestyleDefid` INT(11) NOT NULL,
  `lifestyleDefinition` VARCHAR(300) NOT NULL,
  `measuredBy` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`lifestyleDefid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`dailysuggestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`dailysuggestions` (
  `dailysuggId` INT(11) NOT NULL,
  `lifestyleDefId` INT(11) NOT NULL,
  `motivationalSuggestion` VARCHAR(300) NOT NULL,
  `improvemetSuggestions` VARCHAR(300) NOT NULL,
  `date` INT(11) NOT NULL,
  PRIMARY KEY (`dailysuggId`),
  INDEX `lifestyleDefId` (`lifestyleDefId` ASC),
  CONSTRAINT `dailysuggestions_ibfk_1`
    FOREIGN KEY (`lifestyleDefId`)
    REFERENCES `lifecoach`.`lifestylemeasuremnt` (`lifestyleDefid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`healthmeasurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`healthmeasurement` (
  `healthmeasureDefId` INT(11) NOT NULL,
  `healthmeasureDefinition` VARCHAR(300) NOT NULL,
  `measuredBy` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`healthmeasureDefId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`healthgoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`healthgoal` (
  `goalId` INT(11) NOT NULL,
  `healthmeasureDefid` INT(11) NOT NULL,
  `measuredBy` VARCHAR(300) NOT NULL,
  `goalValue` FLOAT NOT NULL,
  `duration` DATE NOT NULL,
  PRIMARY KEY (`goalId`),
  INDEX `lifestylemeasureDefid` (`healthmeasureDefid` ASC),
  INDEX `healthmeasureDefid` (`healthmeasureDefid` ASC),
  CONSTRAINT `healthgoal_ibfk_1`
    FOREIGN KEY (`healthmeasureDefid`)
    REFERENCES `lifecoach`.`healthmeasurement` (`healthmeasureDefId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`person` (
  `perosnId` INT(11) NOT NULL,
  `firstName` VARCHAR(300) NOT NULL,
  `lastName` VARCHAR(300) NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  `userName` VARCHAR(300) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `createdDate` DATE NOT NULL,
  `careGiverId` INT NULL,
  PRIMARY KEY (`perosnId`),
  INDEX `careGiverId_idx` (`careGiverId` ASC),
  CONSTRAINT `careGiverId`
    FOREIGN KEY (`careGiverId`)
    REFERENCES `lifecoach`.`CareGiiver` (`careGiverId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`healthmeasurehistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`healthmeasurehistory` (
  `healthmeasureHistoryid` VARCHAR(300) NOT NULL,
  `personId` INT(11) NOT NULL,
  `healthmeasureDefid` INT(11) NOT NULL,
  `healthValue` INT(11) NOT NULL,
  `date` INT(11) NOT NULL,
  `isCurrent` TINYINT(1) NULL,
  PRIMARY KEY (`healthmeasureHistoryid`),
  INDEX `healthmeasureDefid` (`healthmeasureDefid` ASC),
  INDEX `personId` (`personId` ASC),
  CONSTRAINT `healthmeasurehistory_ibfk_1`
    FOREIGN KEY (`healthmeasureDefid`)
    REFERENCES `lifecoach`.`healthmeasurement` (`healthmeasureDefId`),
  CONSTRAINT `healthmeasurehistory_ibfk_2`
    FOREIGN KEY (`personId`)
    REFERENCES `lifecoach`.`person` (`perosnId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`lifestylegoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`lifestylegoal` (
  `goalId` INT(11) NOT NULL,
  `lifestylemeasureDefid` INT(11) NOT NULL,
  `measuredBy` VARCHAR(300) NOT NULL,
  `goalValue` FLOAT NOT NULL,
  `duration` DATE NOT NULL,
  PRIMARY KEY (`goalId`),
  INDEX `lifestylemeasureDefid` (`lifestylemeasureDefid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`lifestylemeasurehistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`lifestylemeasurehistory` (
  `lifestylemeasureId` INT(11) NOT NULL,
  `lifestyleDefid` INT(11) NOT NULL,
  `personId` INT(11) NOT NULL,
  `lifestylevalue` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  `IsCurrent` TINYINT(1) NULL,
  PRIMARY KEY (`lifestylemeasureId`),
  INDEX `lifestyleDefid` (`lifestyleDefid` ASC),
  INDEX `personId` (`personId` ASC),
  CONSTRAINT `lifestylemeasurehistory_ibfk_1`
    FOREIGN KEY (`lifestyleDefid`)
    REFERENCES `lifecoach`.`lifestylemeasuremnt` (`lifestyleDefid`),
  CONSTRAINT `lifestylemeasurehistory_ibfk_2`
    FOREIGN KEY (`personId`)
    REFERENCES `lifecoach`.`person` (`perosnId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lifecoach`.`reminder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lifecoach`.`reminder` (
  `reminderId` INT(11) NOT NULL,
  `personId` INT(11) NOT NULL,
  `appointmentType` INT(11) NOT NULL,
  `appointmentDescription` INT(11) NOT NULL,
  `date` INT(11) NOT NULL,
  `time` INT(11) NOT NULL,
  PRIMARY KEY (`reminderId`),
  INDEX `personId` (`personId` ASC),
  CONSTRAINT `reminder_ibfk_1`
    FOREIGN KEY (`personId`)
    REFERENCES `lifecoach`.`person` (`perosnId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

